services:
  hello_haproxy:
    image: haproxy:alpine
    container_name: hello_haproxy
    profiles:
      - default
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 200M
    volumes:
      - ../config/hello/haproxy:/usr/local/etc/haproxy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      default:
      