name: env_swagger_ui
manifest:
  image: swaggerapi/swagger-ui
  restart: unless-stopped
  deploy:
    resources:
      limits:
        memory: 50M
  volumes:
    - ../../config/env/env_swagger_ui/swagger-config.json:/usr/share/nginx/html/swagger-config.json
  profiles:
    - env
  environment:
      CONFIG_URL: swagger-config.json
      URL: ""
  networks:
    default: {}
