include:
  - path: compose/env/env-haproxy.compose.yaml
  - path: compose/env/env-kafka.compose.yaml
  - path: compose/env/env-kafka-ui.compose.yaml
  - path: compose/env/env-pgadmin.compose.yaml
  - path: compose/env/env-postgres.compose.yaml
  - path: compose/env/env-swagger-ui.compose.yaml
  - path: compose/env/env-keycloak.compose.yaml

networks:
  default: {}
