version: "3.9"

include:
  - path: compose/env/env_haproxy.compose.yaml
  - path: compose/env/env_kafka.compose.yaml
  - path: compose/env/env_kafka_ui.compose.yaml
  - path: compose/env/env_pgadmin.compose.yaml
  - path: compose/env/env_postgres.compose.yaml

networks:
  default:
