- path: ''
  name: kafka_ui_local_example_com
  hostname: kafka-ui.local.example.com
  proxies:
  - servers:
    - check: true
      port: 8080
      optional: false
      hostname: env-kafka-ui
    path: /
  port: 80
- path: ''
  name: pgadmin_local_example_com
  hostname: pgadmin.local.example.com
  proxies:
  - servers:
    - check: true
      port: 80
      optional: false
      hostname: env-pgadmin
    path: /
  port: 80
